name: interlog
version: 0.1.0.0
synopsis: whatever
description: |
  Static site builder, but for gopherholes. Manage phlogs with tags, use the Markdown renderer and Mustache templating system.
homepage: https://github.com/someodd/interlog
bug-reports: https://github.com/someodd/interlog/issues
license: GPL-3.0-only
license-file: LICENSE
author: someodd
maintainer: hi@someodd.zip
category: Network
extra-source-files:
  - README.md
  - CHANGELOG.md
tested-with: GHC==9.10.2

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Werror

dependencies:
  - base
  - text
  - unix
  - time
  - bytestring
  - filepath
  - directory

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - DeriveAnyClass
    - OverloadedRecordDot
    - DuplicateRecordFields
  default-language: GHC2021

executables:
  interlog:
    main: Main.hs
    source-dirs: app
    dependencies:
      - interlog
    autogen-modules:
      - Paths_interlog
    other-modules:
      - Paths_interlog
    default-extensions:
      - OverloadedStrings
      - DeriveGeneric
      - DeriveAnyClass
      - OverloadedRecordDot
    default-language: GHC2021